services:
  web:
    image: mujtaba2626/phpuserproject-web:v1
    container_name: first_project_dev_web_container
    ports:
      - "8081:80"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - first_project_network

  db:
    image: mysql:8.0
    container_name: first_project_dev_db_container
    env_file:
      - .env
    volumes:
      - first_project_dev_db_data:/var/lib/mysql
      - ./my_init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - first_project_network

volumes:
  first_project_dev_db_data:

networks:
  first_project_network:
