name: first_project

services:
  web:
    image: mujtaba2626/phpuserproject-web:latest
    ports:
      - "8081:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./my_init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db_data:

networks:
  app_network: